---
title: "What are the chances?"
author: "by Edneide Ramalho"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
output: 
    html_document:
      highlight: textmate
      logo: logo.png
      theme: flatly
      number_sections: yes
      toc: yes
      toc_float:
        collapsed: yes
        smooth_scroll: no
---

```{r, echo = FALSE}
htmltools::img(src = knitr::image_uri(file.path("/Users/edneideramalho/Documents/GitHub/Data_Science/R_Scripts_and_Projects/logo-stat-tech-color-horiz.png")),
               alt = 'logo',
               style = 'position:absolute; top:0; right:0; padding:10px; width: 220px; height: 110px')
```

# Sampling from a data frame

```{r}
library(dplyr)
name <- c("Amir", "Brian", "Claire", "Damian")
n_sales <- c(178, 126, 75, 69)
sales_counts <- tibble::tibble(name = name,
                               n_sales = n_sales)
```

```{r}
set.seed(5)
sales_counts %>% 
  sample_n(1)
```

```{r}
set.seed(5)
sales_counts %>% 
  sample_n(2)
```

```{r}
sales_counts %>% 
  sample_n(2, replace = TRUE)
```

```{r}
sample(sales_counts, 5, replace = TRUE)
```

```{r}
library(readr)
seller_1 <- read_csv("seller_1.csv")
# Count the dealsfor each product
amir_deals <- seller_1
amir_deals %>%
  count(product)
```

-   Create a new column called `prob` by dividing `n` by the total number of deals Amir worked on.

```{r}
amir_deals %>% 
  count(product) %>% 
  mutate(prob = n/sum(n))
```

-   Set the random seed to `31`.

-   Take a sample of 5 deals **without** replacement.

```{r}
# Set random seed to 31
set.seed(31)

# Sample 5 deals without replacement
amir_deals %>%
  sample_n(5, replace = FALSE)
```

-   Take a sample of 5 deals **with** replacement.

```{r}
# Set random seed to 31
set.seed(31)

# Sample 5 deals with replacement
amir_deals %>%
  sample_n(5, replace = TRUE)

```

# Discrete distributions
